### PR TITLE
Added NYU Code of Conduct to requirements, as it should be.

### PR DESCRIPTION
**Pull request by stefancherubin**

### CODE REVIEW

**Comment by NicholasLYang** [comment]
Do we need this on the application? Could we just put this in the confirmation part?

**Comment by stefancherubin** [comment]
I put it on the application only because it was on last year's application. Though, If we make a confirmation page for those who are accepted, we can move the nyu specific checkboxes there.

**Comment by NicholasLYang** [comment]
Yeah let's do that. I kinda don't want to add more stuff to the existing form

**Comment by stefancherubin** [comment]
Closing this, since all this was moved to the new PR

**Pull request closed without merging**
